### ISSUE TITLE
Feature suggestion: Absolute positioning for Touchscreen

### ISSUE THREAD

**Issue by Diamantaeres** [zoeyjodon/moonlight-N3DS#14]
Hello there!

I have installed and tested this version of Moonlight and I am on my New 3DS and I am astonished of the results!
It wprks really well on the device, despite its limitations.

The thing I like more is the way the touchscreen is used as a touchpad.
In two minutes, I naturally got inclined to it and I started to use it spontaneously without even thinking of it.

So, I want to ask you to consider an option that is my favorite one in other versions of the app: 
the possibility to have an option to enable an absolute positioning mode for the touchscreen, meaning that instead of moving the pen to move the mouse around, the points you touch/click matches the respective position on the screen.

I want you to evaluate if this worth it, because there might be some pro and cons.

Pro:
You can directly interact with the elements on screen, as the fact itself you touch them equals to a click (including the opportunity to drag the elements or select areas), instead of moving around and then clicking.

Con:
As there are two screen - and obviously the stream is shown on the upper, which is not touch, as it's the bigger - it might not very intuitive that the lower screen works in this way while being black, so it might be necessary to duplicate the screen on both of them, which might consume more resources I guess.

Thank you for your time and best regards.

**Comment by zoeyjodon** [comment]
Would it be acceptable if I just had the video stream to the bottom screen instead of duplicating the images for both screens? Displaying duplicate images would slow down the framerate, so it would be more efficient to just have the video stream display on the bottom screen when using absolute touch positioning. 

We would lose out on that sweet sweet top screen resolution though, so it would be a tradeoff. I just wanna gauge people's preferences before I start working on this.

**Comment by Diamantaeres** [comment]
Hello there!

It completely makes sense to me, if it is too much effort in terms of resources for the console:
If you are in absolute positioning, you just use the touchscreen, if you are not (current standard mode), you use the upper one and lower as touchpad as it currently is, which is still brilliant.

Thank you!

**Comment by zoeyjodon** [comment]
Added this feature, and I was even able to add absolute touch while displaying video on both the top and bottom screens!

**Comment by Diamantaeres** [comment]
Hello and sorry for returning on this:
The absolute positioning is applied only on both screen view, but this makes impossible to touch/interact with the elements on the top one, as it is not touch (also, the ratio in this way is stretched vertically, which is not great to see).

Would it be possible to separate the absolute position option from the dual screen view?

Eventually, by either making a duplicated screen view (whole screen displaying the same as duplicated on both top and down screens) or by showing the video only in the bottom one.

Thank you!

**Comment by zoeyjodon** [comment]
No worries! I actually added the feature in that C++ upgrade PR. The latest stuff hasn't been versioned and released yet, but if you installed the build from that MR it should give you options for "dual screen (mirror)" and "bottom screen" that do what you're talking about.

https://github.com/zoeyjodon/moonlight-N3DS/actions/runs/9333187359

**Comment by Diamantaeres** [comment]
Hello and thank you for your reply.

No rush, I will wait for it to be released to get it.

Thank you!
