### ISSUE TITLE
RTSP handshake failed

### ISSUE THREAD

**Issue by jaysonsolis** [zoeyjodon/moonlight-N3DS#16]
Host PC is running Sunshine 0.22.2

Client is a New3DS XL

![PXL_20240316_053733730](https://github.com/zoeyjodon/moonlight-N3DS/assets/51274884/d3631bdd-5524-4ffb-895e-05dcf34ac718)

**Comment by RoblKyogre** [comment]
bit on the late side but should be fixed in #18, will most likely be in the next release or you can download a nightly build in [actions](https://github.com/zoeyjodon/moonlight-N3DS/actions) if you want to try it now

**Comment by zoeyjodon** [comment]
Closing this now that I've released the fix!
