### ISSUE TITLE
ndspInit() failed 

### ISSUE THREAD

**Issue by moooooncrescent** [zoeyjodon/moonlight-N3DS#19]
I use new 2ds xl
**_NVidia Geforce Experience version:_3.27.0.120
**Moonlight Embedded version:1.0.1
**Moonlight Embedded source:https://github.com/zoeyjodon/moonlight-N3DS/releases/tag/v1.0.1
**Moonlight Embedded running on: win 10
**Moonlight Embedded running on distribution: win 10
Error audio stream start. On old 3ds stream working fine.
![photo_2024-03-17_03-32-16](https://github.com/zoeyjodon/moonlight-N3DS/assets/38298370/2c0781fd-4c47-46d6-b2bf-c71a9ab3d08b)

**Comment by moooooncrescent** [comment]
![image](https://github.com/zoeyjodon/moonlight-N3DS/assets/38298370/51506471-0ec0-4fc2-b760-f461fa9f9934)
In sunshine, after I select pair, I'm stuck on this screen and didn't get connection code

**Comment by zoeyjodon** [comment]
Iirc this is an issue with DSP not being set up on your 3DS. You should be able to run DSP Dump and have sound work afterwards:

https://gbatemp.net/threads/release-dsp-dump.423860/

**Comment by moooooncrescent** [comment]
I install it, thanks! But...

Now i got this error:
![image](https://github.com/zoeyjodon/moonlight-N3DS/assets/38298370/1f1f9d61-f5e4-46fc-929b-e942eec65fdc)

**Comment by Akimyou** [comment]
> Iirc this is an issue with DSP not being set up on your 3DS. You should be able to run DSP Dump and have sound work afterwards:
> 
https://github.com/Cruel/DspDump this  DspDump was to old and not work for me.

if any one have the same problem, and can try this one: https://github.com/zoogie/DSP1/releases
