### ISSUE TITLE
Connection terminated with error: -1

### ISSUE THREAD

**Issue by jakobyDan** [zoeyjodon/moonlight-N3DS#21]
i keep getting this error and i dont know how to fix it.
can someone help please?

![IMG_7148](https://github.com/zoeyjodon/moonlight-N3DS/assets/106186558/827a3ec9-ab69-4428-a40a-a4676a7e464a)

**Comment by RoblKyogre** [comment]
dupe of #16 and/or #15, should be fixed in #18, will most likely be in the next release or you can download a nightly build in [actions](https://github.com/zoeyjodon/moonlight-N3DS/actions) if you want to try it now

**Comment by zoeyjodon** [comment]
Closing this as a duplicate, if the issue persists with v1.1.0, please make a new issue and include screenshots with debugging enabled for more info
