### ISSUE TITLE
Feature suggestion: ability to map different buttons

### ISSUE THREAD

**Issue by soapheadd** [zoeyjodon/moonlight-N3DS#22]
How could i swap button R with ZR, and L with ZL? Also the option to swap a/b and x/y to match xbox layout.
I know the easy option would be to change the keybind in the game, but i cant in my case

**Comment by RoblKyogre** [comment]
#11 implements what you're requesting, will most likely be in the next release or you can download a nightly build in [actions](https://github.com/zoeyjodon/moonlight-N3DS/actions) if you want to try it now

**Comment by zoeyjodon** [comment]
Just released the new version which includes this feature! So I'm gonna close this ticket.
