### ISSUE TITLE
Feature Request: Bottom Screen Keyboard

### ISSUE THREAD

**Issue by getBoolean** [zoeyjodon/moonlight-N3DS#29]
**Is your feature request related to a problem? Please describe.**
Some games may require keyboard input, but it doesn't look like it is possible to open the Windows keyboard.

**Describe the solution you'd like**
Either a button to open the Windows touchscreen keyboard, or add a keyboard to the bottom touch screen.

**Comment by zoeyjodon** [comment]
Added this feature!

**Comment by getBoolean** [comment]
Thanks!
