### ISSUE TITLE
Nvidia GeForce error 116

### ISSUE THREAD

**Issue by Watermelon1263** [zoeyjodon/moonlight-N3DS#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Connection to Nvidia gamestream

**Describe alternatives you've considered**

**Additional context**
![20240505_145904](https://github.com/zoeyjodon/moonlight-N3DS/assets/116121900/ed1385ef-8d85-46c4-99b8-8f5f760ea3f7)

**Comment by zoeyjodon** [comment]
Could you enable "debug logs" in your Moonlight settings, try connecting again, then post another screenshot of the logs so I can get some more info?

**Comment by starman723** [comment]
Where are the debug logs outputted to?

**Comment by zoeyjodon** [comment]
They're just printed directly to the top display. You wont need to search for a file or anything, just grab a screenshot of the error like you did before, but with debug logs enabled.

**Comment by starman723** [comment]
![20240510_150417](https://github.com/zoeyjodon/moonlight-N3DS/assets/116121900/b3775177-8997-4fd9-97ac-2375c2d44886)
![20240510_150011](https://github.com/zoeyjodon/moonlight-N3DS/assets/116121900/c8941fab-829d-4916-a0c8-a0614b883e9e)

**Comment by zoeyjodon** [comment]
Could you try upgrading to v0.23.1 and testing the C++ build? My local tests have been working for both GameStream and Sunshine, although my setup was also working before so idk if it will fix your setup too.
https://github.com/zoeyjodon/moonlight-N3DS/actions/runs/9309462288

**Comment by starman723** [comment]
I tried updating and got the same error. How do I use the C++ build?

**Comment by starman723** [comment]
When I'm using the c++ build and I put the pin into sunshine it doesn't update on my 3ds
