### ISSUE TITLE
small question: how do i quit stream?

### ISSUE THREAD

**Issue by alchemistake** [zoeyjodon/moonlight-N3DS#35]
I clicked every button i couldn't figure it out :/
What is the combo to open the quit stream menu?

**Comment by Uncraftbar** [comment]
Just the normal Moonlight button combo
L+R+Start+Select

Unfortnunatly, it just quits moonlight all together, doesnt bring the menu back up

**Comment by zoeyjodon** [comment]
> Just the normal Moonlight button combo L+R+Start+Select
> 
> Unfortnunatly, it just quits moonlight all together, doesnt bring the menu back up

Thanks for reminding me! Part of why I wanted to do a C++ overhaul was to make returning to the main menu easier.

**Comment by zoeyjodon** [comment]
Just merged changes that keep the app from closing after exiting the stream! The exit command is still the same (L+R+Select+Start)
