### ISSUE TITLE
No audio with sunshine v21

### ISSUE THREAD

**Issue by pcs3rd** [zoeyjodon/moonlight-N3DS#36]
**Describe the bug**
There is no audio while using moonlight-3ds with sunshine. Attempts to reproduce on other clients are unsuccessful.  
The DSP is dumped.
The nn2dscl does complain about some frames being dropped.

**To Reproduce**
1. Start stream
2. No audio 

**Expected behavior**
There should be audio

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser Chrome 
 - sunshine Version 21

**Smartphone (please complete the following information):**
 - Device: nn2dsxl
 - OS: Luma3DS
 - Version v13.0.2

**Additional context**

**Comment by zoeyjodon** [comment]
Could you try upgrading to v0.23.1 and testing the C++ build? My local tests with those builds seem to have the audio working just fine.
https://github.com/zoeyjodon/moonlight-N3DS/actions/runs/9309462288

**Comment by fallenexistence0** [comment]
I am a month late, but could you post the sunshine logs? What does it say? Since you are on linux, you may have run sunshine as root which causes problems with the audio.

**Comment by pcs3rd** [comment]
I don't have this environment anymore. I'll reopen if I can reproduce. 
https://nixos.wiki/wiki/Sunshine should generate a similar environment.
