### ISSUE TITLE
(Feature Request) Touchscreen L3 and R3 mapping edit (enable dragging the touch input between the L3, L3+R3, and R3 buttons)

### ISSUE THREAD

**Issue by dude98** [zoeyjodon/moonlight-N3DS#37]
**Is your feature request related to a problem? Please describe.**
putting multiple touch inputs causes the 3ds to find the middle point between the presses, because of that and the button already present in between L3 and R3 activating both, why is it set so that pressing a touchscreen button disables the others until it stops receiving input?

** Describe the solution you'd like**
by making it so that you can drag the touch input between all 3 without needing to let go, you can press your thumbs on L3 and R3 to hit both, and if you remove your thumb off of only one of the buttons it'll only let go of the one you removed your thumb from, rather than keeping both held until you completely let go of the touchscreen.

**Additional context**
a setup like this is something that would work very well for games that have you pressing the thumbsticks a lot.

**Comment by zoeyjodon** [comment]
Added!
