### ISSUE TITLE
Black and white, screen shifted

### ISSUE THREAD

**Issue by Zaybomb** [zoeyjodon/moonlight-N3DS#39]
**Describe the bug**
The screan is black and white and seems to be shifted to the left so far that it wraps around to the right again.

**To Reproduce**
Just running the stream.

**Expected behavior**
Colour, and lined up

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
![20240531_190533](https://github.com/zoeyjodon/moonlight-N3DS/assets/86151801/8105f5ad-9a6e-4db1-986f-09690836feee)

**Comment by Zaybomb** [comment]
It does have blue and orange streaking aswell

**Comment by zoeyjodon** [comment]
What are your stream settings? (Width, height, fps, bitrate, etc)

**Comment by Zaybomb** [comment]
400x240. 30 fps. 300 bitstream

**Comment by Zaybomb** [comment]
Didn't change anything but the bitstream

**Comment by zoeyjodon** [comment]
Does changing the bitrate back to 1000 change anything?

**Comment by Zaybomb** [comment]
No

**Comment by Zaybomb** [comment]
Neither do other bitrates

**Comment by zoeyjodon** [comment]
Darn. Could you try out the C++ upgrade? There's a change to the renderer in there that might affect things:

https://github.com/zoeyjodon/moonlight-N3DS/actions/runs/9309462288

**Comment by Zaybomb** [comment]
I already switched to it after posting this and reading other people's issues

**Comment by Zaybomb** [comment]
Sounds like this is a new issue, no?

**Comment by Zaybomb** [comment]
Oh wait a second

**Comment by Zaybomb** [comment]
It works just fine if I attempt to connect to my other laptop

**Comment by Zaybomb** [comment]
Updated sunshine and it's all good
