### ISSUE TITLE
-1 Error in Old 3ds. Cannot Connect

### ISSUE THREAD

**Issue by OMatheusLevi** [zoeyjodon/moonlight-N3DS#46]
When I connect my Old 3ds to moonlight, an error appears on the screen saying that hardware decoding is only available for the new 3ds and gives an error called -1, can anyone help me?

**Comment by RoblKyogre** [comment]
the old 3ds does not support hardware decoding, so go to stream settings and disable `hwdecode` to be able to use this on your old 3ds.

**Comment by OMatheusLevi** [comment]
> o antigo 3ds não suporta decodificação de hardware, então vá para as configurações de transmissão e desative `hwdecode`para poder usar isso no seu antigo 3ds.

Omggg, thankss its fix
